/* This file is used for rest.nvim (Lightweight Postman but in Neovim) */

/* Get Accounts */
GET http://localhost:3380/account
Content-Type: application/json

/* Get specific account via id */
GET http://localhost:3380/account/123653
Content-Type: application/json
